theme: jekyll-theme-minimal
title: Matteo Monzali
description: Documentary, environmental and scientific photography portfolio by Matteo Monzali.
url: "https://matteomonzali.com"
baseurl: ""
lang: en-US
